# Generated by Django 3.1.3 on 2021-01-09 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('Files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('File_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Files.files')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.member')),
            ],
        ),
    ]
